#!/usr/bin/env python

"""View informations of hdf5 data files.

Authors: Shifan Zuo
Date:    2016-01-06
Email:   sfzuo@bao.ac.cn
Usage:   h5info [-h] h5files [h5files ...]
"""

import argparse


def h5_info(args):
    """View informations of a hdf5 data file.
    """
    try:
        import cPickle as pickle
    except:
        import pickle
    import h5py

    def print_info(name, obj):
        try:
            shape = obj.shape # 'Group' object has no attribute 'shape'
            print name, '  shape = ', shape
        except:
            print name
        # print group/dataset attributes
        for attrs_name, attrs_value in obj.attrs.iteritems():
            try:
                attrs_value = pickle.loads(attrs_value) # unpickle pickled data
            except:
                pass
            print '%s.attrs["%s"]:' % (name, attrs_name), attrs_value

    for h5file in args.h5files:
        print 'File: ', h5file
        with h5py.File(h5file, 'r') as f:
            # print file attributes
            for attrs_name, attrs_value in f.attrs.iteritems():
                try:
                    attrs_value = pickle.loads(attrs_value) # unpickle pickled data
                except:
                    pass
                print '/.attrs["%s"]:' % (attrs_name), attrs_value
            f.visititems(print_info)
        print '-' * 60


parser = argparse.ArgumentParser(description='View informations of a hdf5 data file.')
parser.add_argument('h5files', type=str, nargs='+', help='Input hdf5 files.')
parser.set_defaults(func=h5_info)

args = parser.parse_args()
args.func(args)


